[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["error_handling"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "error_handling"
  org = "juanpablovadell"
  version = "3.1.1"

