openapi: 3.0.1
info:
  title: /
  version: 3.1.1
servers:
- url: "{server}:{port}/"
  variables:
    server:
      default: http://localhost
    port:
      default: "8090"
paths:
  /invoke:
    post:
      operationId: postInvoke
      parameters:
      - name: option
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "404":
          description: NotFound
        "400":
          description: BadRequest
        "500":
          description: Internal server error
          content:
            text/plain:
              schema:
                type: string
components: {}
